CREATE DATABASE REATAIL;

--CUSTOMERS
DROP TABLE IF EXISTS CUSTOMERS CASCADE;

CREATE TABLE CUSTOMERS (
	CUSTOMER_ID INT PRIMARY KEY,
	CUSTOMER_NAME VARCHAR(100),
	CITY VARCHAR(50),
	SEGMENT VARCHAR(50),
	SIGNUP_DATE DATE
);

--PRODUCTS
DROP TABLE IF EXISTS PRODUCTS CASCADE;

CREATE TABLE PRODUCTS (
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCT_NAME VARCHAR(100),
	CATEGORY VARCHAR(50),
	COST_PRICE NUMERIC,
	SELLING_PRICE NUMERIC
);

--ORDERS
DROP TABLE IF EXISTS ORDERS CASCADE;

CREATE TABLE ORDERS (
	ORDER_ID INT PRIMARY KEY,
	CUSTOMER_ID INT REFERENCES CUSTOMERS (CUSTOMER_ID),
	ORDER_DATE DATE,
	WAREHOUSE_ID INT
);

--ORDERS_DETAILS
DROP TABLE IF EXISTS ORDER_DETAILS CASCADE;

CREATE TABLE ORDER_DETAILS (
	ORDER_DETAIL_ID INT PRIMARY KEY,
	ORDER_ID INT REFERENCES ORDERS (ORDER_ID),
	PRODUCT_ID INT REFERENCES PRODUCTS (PRODUCT_ID),
	QUANTITY INT,
	DISCOUNT NUMERIC,
	REVENUE NUMERIC,
	PROFIT NUMERIC
);

--INVENTORY
DROP TABLE IF EXISTS INVENTORY CASCADE;

CREATE TABLE INVENTORY (
	PRODUCT_ID INT REFERENCES PRODUCTS (PRODUCT_ID),
	STOCK_QUANTITY INT,
	LAST_RESTOCK_DATE DATE
);

--RETURNS
DROP TABLE IF EXISTS RETURNS CASCADE;

CREATE TABLE RETURNS (
	RETURNS_ID INT PRIMARY KEY,
	ORDER_ID INT REFERENCES ORDERS (ORDER_ID),
	RETURN_DATE DATE,
	RETURN_REASON VARCHAR(100)
);

SELECT
	COUNT(*)
FROM
	CUSTOMERS;

SELECT
	COUNT(*)
FROM
	PRODUCTS;

SELECT
	COUNT(*)
FROM
	INVENTORY;

SELECT
	COUNT(*)
FROM
	ORDERS;

SELECT
	COUNT(*)
FROM
	ORDER_DETAILS;

SELECT
	COUNT(*)
FROM
	RETURNS;

--REVENUE ANALYSIS - 1. Total Revenue & Profit
SELECT
	SUM(REVENUE) AS TOTAL_REVENUE,
	SUM(PROFIT) AS TOTAL_PROFIT
FROM
	ORDER_DETAILS;

--2. Monthly Revenue Trend
SELECT
	DATE_TRUNC('month', O.ORDER_DATE) AS MONTH,
	SUM(OD.REVENUE) AS MONTHLY_REVENUE
FROM
	ORDERS O
	JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	MONTH
ORDER BY
	MONTH;

--3. Running Total
SELECT
	MONTH,
	SUM(MONTHLY_REVENUE) OVER (
		ORDER BY
			MONTH
	) AS RUNNING_TOTAL
FROM
	(
		SELECT
			DATE_TRUNC('month', O.ORDER_DATE) AS MONTH,
			SUM(OD.REVENUE) AS MONTHLY_REVENUE
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			MONTH
	);

--PROFITABILITY - 4. Top 10 Products By Profit
SELECT
	P.PRODUCT_NAME,
	SUM(OD.PROFIT) AS TOTAL_PROFIT
FROM
	ORDER_DETAILS OD
	JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.PRODUCT_NAME
ORDER BY
	TOTAL_PROFIT DESC
LIMIT
	10;

--5. Loss Making Products
SELECT
	P.PRODUCT_NAME,
	SUM(OD.PROFIT) AS TOTAL_PROFIT
FROM
	ORDER_DETAILS OD
	JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.PRODUCT_NAME
HAVING
	SUM(OD.PROFIT) < 0;

--CUSTOMER INTELLIGENCE - 6. Recency
SELECT
	CUSTOMER_ID,
	MAX(ORDER_DATE) AS LAST_ORDER
FROM
	ORDERS
GROUP BY
	CUSTOMER_ID;

--7. Frequency
SELECT
	CUSTOMER_ID,
	COUNT(ORDER_ID) AS FREQUENCY
FROM
	ORDERS
GROUP BY
	CUSTOMER_ID;

--8. Monetary
SELECT
	O.CUSTOMER_ID,
	SUM(OD.REVENUE) AS MONETARY
FROM
	ORDERS O
	JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	O.CUSTOMER_ID;

--9. RFM Segmentation (NTILE)
WITH
	RFM AS (
		SELECT
			O.CUSTOMER_ID,
			MAX(O.ORDER_DATE) AS LAST_ORDER,
			COUNT(O.ORDER_ID) AS FREQUENCY,
			SUM(OD.REVENUE) AS MONETARY
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			O.CUSTOMER_ID
	)
SELECT
	*,
	NTILE(4) OVER (
		ORDER BY
			MONETARY DESC
	) AS MONETARY_SEGMENT
FROM
	RFM;

--INVENTORY INTELLIGENCE - 10. Dead Stock(No Sale In 90 Days)
SELECT
	P.PRODUCT_NAME
FROM
	PRODUCTS P
	LEFT JOIN ORDER_DETAILS OD ON P.PRODUCT_ID = OD.PRODUCT_ID
	LEFT JOIN ORDERS O ON OD.ORDER_ID = O.ORDER_ID
GROUP BY
	P.PRODUCT_NAME
HAVING
	MAX(O.ORDER_DATE) < CURRENT_DATE - INTERVAL '90 days';

--11. Inventory Turnover
SELECT
	P.PRODUCT_NAME,
	SUM(OD.QUANTITY) / AVG(I.STOCK_QUANTITY) AS TURNOVER_RATIO
FROM
	ORDER_DETAILS OD
	JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
	JOIN INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
GROUP BY
	P.PRODUCT_NAME;

--OPERATIONAL - 12. Return Rate
SELECT
	COUNT(DISTINCT R.ORDER_ID) * 100.0 / COUNT(DISTINCT O.ORDER_ID) AS RETURN_RATE
FROM
	ORDERS O
	LEFT JOIN RETURNS R ON O.ORDER_ID = R.ORDER_ID;

--13. Most Common Return Reason
SELECT
	RETURN_REASON,
	COUNT(*) AS TOTAL
FROM
	RETURNS
GROUP BY
	RETURN_REASON
ORDER BY
	TOTAL DESC;

--14. Category-wise Revenue Contribution %
SELECT
	P.CATEGORY,
	SUM(OD.REVENUE) AS CATEGORY_REVENUE,
	ROUND(
		SUM(OD.REVENUE) * 100.0 / SUM(SUM(OD.REVENUE)) OVER (),
		2
	) AS CONTRIBUTION_PERCENT
FROM
	ORDER_DETAILS OD
	JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.CATEGORY
ORDER BY
	CONTRIBUTION_PERCENT DESC;

--15. Profit Margin By Category
SELECT
	P.CATEGORY,
	SUM(OD.PROFIT) AS TOTAL_PROFIT,
	SUM(OD.REVENUE) AS TOTAL_REVENUE,
	ROUND(SUM(OD.PROFIT) * 100.0 / SUM(OD.REVENUE), 2) AS PROFIT_MARGIN_PERCENT
FROM
	ORDER_DETAILS OD
	JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.CATEGORY
ORDER BY
	PROFIT_MARGIN_PERCENT DESC;

--16. Discount Impact Analysis
SELECT
	CASE
		WHEN DISCOUNT >= 0.30 THEN 'High Discount'
		WHEN DISCOUNT >= 0.15 THEN 'Medium Discount'
		ELSE 'Low Discount'
	END AS DISCOUNT_LEVEL,
	SUM(REVENUE) AS TOTAL_REVENUE,
	SUM(PROFIT) AS TOTAL_PROFIT
FROM
	ORDER_DETAILS
GROUP BY
	DISCOUNT_LEVEL
ORDER BY
	TOTAL_PROFIT;

--17. Top 20% Revenue Customers (Pareto)
WITH
	CUSTOMER_REVENUE AS (
		SELECT
			O.CUSTOMER_ID,
			SUM(OD.REVENUE) AS TOTAL_REVENUE
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			O.CUSTOMER_ID
	),
	RANKED AS (
		SELECT
			*,
			NTILE(5) OVER (
				ORDER BY
					TOTAL_REVENUE DESC
			) AS REVENUE_GROUP
		FROM
			CUSTOMER_REVENUE
	)
SELECT
	*
FROM
	RANKED
WHERE
	REVENUE_GROUP = 1;

--18. DENSE_RANK Product Profit Ranking
SELECT
	P.PRODUCT_NAME,
	SUM(OD.PROFIT) AS TOTAL_PROFIT,
	DENSE_RANK() OVER (
		ORDER BY
			SUM(OD.PROFIT) DESC
	) AS PROFIT_RANK
FROM
	ORDER_DETAILS OD
	JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
GROUP BY
	P.PRODUCT_NAME;

--19. Revenue At Risk
WITH
	PRODUCT_RETURNS AS (
		SELECT
			OD.PRODUCT_ID,
			COUNT(R.RETURNS_ID) AS TOTAL_RETURNS
		FROM
			ORDER_DETAILS OD
			JOIN RETURNS R ON OD.ORDER_ID = R.ORDER_ID
		GROUP BY
			OD.PRODUCT_ID
	),
	PRODUCT_MARGIN AS (
		SELECT
			PRODUCT_ID,
			SUM(PROFIT) * 100.0 / SUM(REVENUE) AS MARGIN_PERCENT
		FROM
			ORDER_DETAILS
		GROUP BY
			PRODUCT_ID
	)
SELECT
	P.PRODUCT_NAME,
	PR.TOTAL_RETURNS,
	PM.MARGIN_PERCENT
FROM
	PRODUCT_RETURNS PR
	JOIN PRODUCT_MARGIN PM ON PR.PRODUCT_ID = PM.PRODUCT_ID
	JOIN PRODUCTS P ON P.PRODUCT_ID = PR.PRODUCT_ID
WHERE
	PR.TOTAL_RETURNS > 5
	AND PM.MARGIN_PERCENT < 10;

--20. Monthly Profit Growth %
WITH
	MONTHLY_PROFIT AS (
		SELECT
			DATE_TRUNC('month', O.ORDER_DATE) AS MONTH,
			SUM(OD.PROFIT) AS MONTHLY_PROFIT
		FROM
			ORDERS O
			JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
		GROUP BY
			MONTH
	)
SELECT
	MONTH,
	MONTHLY_PROFIT,
	LAG(MONTHLY_PROFIT) OVER (
		ORDER BY
			MONTH
	) AS PREV_MONTH_PROFIT,
	ROUND(
		(
			MONTHLY_PROFIT - LAG(MONTHLY_PROFIT) OVER (
				ORDER BY
					MONTH
			)
		) * 100.0 / LAG(MONTHLY_PROFIT) OVER (
			ORDER BY
				MONTH
		),
		2
	) AS GROWTH_PERCENT
FROM
	MONTHLY_PROFIT;

--21. Customer Lifetime Value(CLV)
SELECT
	O.CUSTOMER_ID,
	SUM(OD.REVENUE) AS LIFETIME_VALUE
FROM
	ORDERS O
	JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	O.CUSTOMER_ID
ORDER BY
	LIFETIME_VALUE DESC;

--22. Warehouse Performance
SELECT
	O.WAREHOUSE_ID,
	SUM(OD.REVENUE) AS WAREHOUSE_REVENUE,
	SUM(OD.PROFIT) AS WAREHOUSE_PROFIT
FROM
	ORDERS O
	JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	O.WAREHOUSE_ID
ORDER BY
	WAREHOUSE_PROFIT DESC;

--23. Average Order Value (AOV)
SELECT
	ROUND(SUM(REVENUE) / COUNT(DISTINCT ORDER_ID), 2) AS AVG_ORDER_VALUE
FROM
	ORDER_DETAILS;

--24. Most Profitable Customers
SELECT
	O.CUSTOMER_ID,
	SUM(OD.PROFIT) AS TOTAL_PROFIT
FROM
	ORDERS O
	JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
GROUP BY
	O.CUSTOMER_ID
ORDER BY
	TOTAL_PROFIT DESC
LIMIT
	10;

--25. Category - Wise Return Rate
SELECT
	P.CATEGORY,
	COUNT(R.RETURNS_ID) * 100.0 / COUNT(DISTINCT O.ORDER_ID) AS RETURN_RATE_PERCENT
FROM
	ORDERS O
	JOIN ORDER_DETAILS OD ON O.ORDER_ID = OD.ORDER_ID
	JOIN PRODUCTS P ON OD.PRODUCT_ID = P.PRODUCT_ID
	LEFT JOIN RETURNS R ON O.ORDER_ID = R.ORDER_ID
GROUP BY
	P.CATEGORY
ORDER BY
	RETURN_RATE_PERCENT DESC;
	